#!/bin/bash

#see skript arhiveerib iga kasutaja kodukataloogi backup kausta

echo -n "Sisesta backup-ks kataloogi:"
read lahtekaust
echo -n "Sisestakuhu backup-i salvestada:"
read sihtkaust
mkdir `echo $sihtkaust`
ls -ld `echo /$sihtkaust`
echo "oled siin:"
echo `pwd`
cd `echo $sihtkaust`
echo "nüüd oled siin:"
echo `pwd`
sleep 2

for filename in $(ls $lahtekaust); do
	result=
	echo $filename
        if [ -f $filename ]; then
                result="$filename is a regular file"
                echo $result
                echo ""
                sleep 2
        else
                if [ -d $filename ]; then
                        result="$filename is a directory Do BACKUP!"
                        echo $result
                        #kuupäeva numbrid välja lõikamine
                        kuupaev=`date +%d.%m.%Y`
                        echo $kuupaev
                        echo $lahtekaust$filename/
                        #kataloogi pakkimine ja arhiveerimine
                        tar -cf $filename.$kuupaev.tar $filename/
                        gzip $filename.$kuupaev.tar
                        #pakitud faili liigutamine loodud backup kausta
                        mv $filename.$kuupaev.tar.gz $sihtkaust
                        echo ""
                        sleep 2
			ls -l `echo $sihtkaust$filename.$kuupaev.tar.gz`
                fi
        fi
done

