#!/bin/bash
# kasutajate lisamise skript
# käsurea kaudu parameetrite arv on $# sees olev number
# meie korral peab olema 1-ne parameeter faili nimi, kus on kasutajate nimed kirjas
if [ $# -ne 1 ]; then
	# kui valesti on, siis veateade
	echo "Kasutusjuhend (sisesta antud kujul): $0 failinimi"
else
	# määrame muutujale "failinimi" 1-ne sisestatud parameeter
	failinimi=$1
	# kontrolline kas  sisestatud failinimi on korras
	if [ -f $failinimi -a -r $failinimi ]; then
		# ning teavitame kasutajad sellest
		echo "fail on korras"
		# paneme tsükli käima senikaua, mitu kasutajad on failis määratud
		for nimi in $(cat $failinimi)
    		do
			# sellega peaks faili sisu olema nähtav, kui fail on kätte saadav
			# ja echo asemel käivitame skripti "lisa_kasutaja"
			kasutajanimi=$(echo "$nimi" |  cut -f1 -d:)
			# kontrollimiseks prindime  failis olevaid kasutajaid
			#echo $nimi
			# kontrollimiseks prindime muutuja $kasutajanimi ekraanile
			#echo $kasutajanimi
			# sellega me laseme lisa_kasutaja skript tööle
			sh lisa_kasutaja $kasutajanimi
			# antud rida võimaldab kasutajale määrata parool
			echo "$nimi" | chpasswd
    		done
	else
    		echo "probleem failiga $failinimi"
  	fi
	# parameetrite kontrolli lõpp
fi

