#!/bin/bash

#skript paigaldab Apache serveri arvutise ning kontrollib kas on juba eelnevalt installitud
APACHE=$(dpkg-query -W -f='${Status}' apache2 2>/dev/null | grep -c 'ok installed')
#kontrollime kas "ok installed" leiab (peab võrduma 0-ga), kui ei siis veateade
if [ $APACHE -eq 0 ]; then
	echo "Paigaldame apache2!"
	apt install apache2
	sleep 2
	echo "Apache2 on paigaldatud!"
#kui võrdub 1-ga, siis teeme:
elif [ $APACHE -eq 1 ]; then
	echo "Apache2 on juba installitud!"
	#vaatame teenuse staatust
	service apache2 status
	sleep 2
	service apache2 start
	sleep 2
	echo "vahetame vaikimisi veebilehte"
	sed -i "s/Apache2 Debian Default Page/Morin Apache Page/g" /var/www/html/index.html
	echo "tehtud"
fi

