#!/bin/bash
# kontrollime sisendit - kui arv sisestatud parameetreid ei võrdu 2, siis veateade
if [ $# -ne 2 ]; then
	# Veateade = $0 - skripti faili nimi + kasutaja + parool
	echo "Kasutusjuhend (sisesta käsk antud kujul): $0 kasutaja_fail parooli_fail"
# kui võrdub 2-ga siis hakkame kasutajaid lisama
else
	# kasutajanimega fail on esimene parameeter, seega tuleb kasutada $1 muutujat
	uname=$1
	# paroolide fail on teine parameeter, siis kasutame $2 muutujat
	pass=$2
	#siin liidame 2 faili kokku ning paneme : vahele (chpasswd jaoks)
	#saab ka muutujale seda määrata var=paste -d":" $uname $pass
	paste -d":" $uname $pass > ./uname_pass
	more ./uname_pass
	# kasutame kasutaja lisamise käsk + bash keskkonda kasutaja jaoks loomine
	# kontrollime kas esimene sisestatud failinimi on õige
	if [ -f $uname -a -r $uname ]; then
		for nimi in $(cat $uname)
        	do
			echo "Fail on $uname KORRAS!"
			# kasutame kasutaja lisamise käsk + bash keskkonda kasutaja jaoks loomine
			useradd $nimi -m -s /bin/bash
			echo "Kasutaja nimega $nimi on lisatud süsteemi!"
			# prindime väljundi  /etc/passwd failist, lõigates loova kasuta nime järgi
			#cat /etc/passwd | grep $kasutajanimi
			# näitame loova kasutaja kodu kataloogi
			# ls -la /home/$kasutajanimi
			# näitame, et /home/ kaustas on loodud meie lisatava kasutaja kodukataloog
		done
	else
			#kui valesti midagi sisetatud, siis veateade
			echo "probleem failiga $uname!"
        	        echo "probleemi kood on $?"
	fi
	ls -la /home/

	# teeme senikaua meil paroole failis on määratud
        for var in $(cat ./uname_pass)
	do
		if [ -f ./uname_pass -a -r ./uname_pass ]; then
			echo "Fail $pass on korras!"
			echo "----------Kontrollime var muutuja: $var   -----------"
			echo "$var" | chpasswd
			##more /etc/shadow | grep ""
		else
			#kui valesti midagi sisetatud, siis veateade
	                echo "probleem failiga $pass!"
        	        echo "probleemi kood on $?"
		fi
	done
rm ./uname_pass
fi
